java:
  runtime:
    version: 11

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ong
      username: admin

ong:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbcUrl:  jdbc:postgresql://localhost:5432/ong
    username: postgres
    password: admin
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres
server:
  error:
    include-message: always
